image:
  - Ubuntu2004

stack: python 3

build: off

install:
- pip install gcovr
- pip install codecov
- pip --version
- python --version
- gcc --version
- gcov --version
- codecov --version

test_script:
- mkdir build
- cd build
- cmake -DYACU_CMAKE_COVERAGE=True -DYACU_CMAKE_TESTS4TESTS=True -DCMAKE_BUILD_TYPE=Debug ..
- cmake --build . --target yacucoverage
- cd ..

after_test:
- gcovr --xml coverage.xml
- codecov --disable gcov --file coverage.xml

on_finish:
  # Upload test results to AppVeyor
  - ps: |
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path ./build/tests4tests.xml))
