image:
  - Ubuntu

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu

stack: python 3

build: off

install:
- pip --version
- python --version
- gcc --version
- gcov --version
- pip install gcovr
- pip install codecov

test_script:
- mkdir build
- cd build
- cmake -DCOVERAGE=True -DCMAKE_BUILD_TYPE=Debug ..
- cmake --build . --target yacucoverage
- cd ..

after_test:
- codecov -X gcov
