image:
  - Ubuntu

environment:
  matrix:
  - job_name: Ubuntu and GCC 7
    APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu

stack: python 3

build: off

install:
- pip install gcovr
- pip install codecov
- pip --version
- python --version
- gcc --version
- which gcc
- gcov --version
- which gcov
- codecov --version

test_script:
- mkdir build
- cd build
- cmake -DCOVERAGE=True -DCMAKE_BUILD_TYPE=Debug ..
- cmake --build . --target yacucoverage
- cd ..

after_test:
- gcovr -r . --xml coverage.xml
- codecov -X gcov --file coverage.xml
