image:
  - Ubuntu2004

stack: python 3

build: off

install:
- pip install gcovr
- pip install codecov
- pip --version
- python --version
- gcc --version
- which gcc
- gcov --version
- which gcov
- codecov --version

test_script:
- mkdir build
- cd build
- cmake -DCOVERAGE=True -DCMAKE_BUILD_TYPE=Debug ..
- cmake --build . --target yacucoverage
- cd ..

after_test:
- codecov
